---
apiVersion: v1
kind: Namespace
metadata:
  name: salabdi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: salabdi
  namespace: salabdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: salabdi
  namespace: ransim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: student-lv1
subjects:
- kind: ServiceAccount
  name: salabdi
  namespace: salabdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: salabdi
  namespace: ricxapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: student-lv1
subjects:
- kind: ServiceAccount
  name: salabdi
  namespace: salabdi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: salabdi
  namespace: salabdi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: salabdi
  namespace: salabdi
---
apiVersion: v1
kind: Secret
metadata:
  name: salabdi
  namespace: salabdi
  annotations:
    kubernetes.io/service-account.name: "salabdi"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: salabdi
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - '*'
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-lv1
  namespace: ricplt
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-lv1
  namespace: ricplt
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student-lv1
  namespace: ricxapp
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---