---
apiVersion: v1
kind: Namespace
metadata:
  name: studas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: studas
  namespace: studas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studas
  namespace: ran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: student
subjects:
- kind: ServiceAccount
  name: studas
  namespace: studas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studas
  namespace: ricxapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: student
subjects:
- kind: ServiceAccount
  name: studas
  namespace: studas
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studas
  namespace: studas
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- kind: ServiceAccount
  name: studas
  namespace: studas
---
apiVersion: v1
kind: Secret
metadata:
  name: studas
  namespace: studas
  annotations:
    kubernetes.io/service-account.name: "studas"
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: studas
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - '*'
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dbaas-appconfig
  namespace: studas
data:
  DBAAS_NODE_COUNT: '1'
  DBAAS_SERVICE_HOST: service-ricplt-dbaas-tcp.ricplt
  DBAAS_SERVICE_PORT: '6379'
