apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student
  namespace: ricplt
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student
  namespace: ricxapp
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student
  namespace: ran
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: student
  namespace: nonrtric
rules:
  - apiGroups:
      - ''
      - extensions
      - apps
      - batch
      - networking.k8s.io
    resources:
      - services
      - pods
      - deployments
      - statefulsets
      - configmaps
    verbs:
      - get
      - list
      - watch
---