apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: open5gs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: ransim
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: ricxapp
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: taisp-ml-infra
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: researcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: researcher
  namespace: srsran
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: researcher
  namespace: default
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: researcher
  namespace: taisp-ml-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: researcher
  namespace: default
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: researcher
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: researcher
  namespace: default
---  
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: researcher
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: researcher
  namespace: default  